---
title: "Manuscript Title"
format:
  docx:
    reference-doc: custom-reference-doc.docx
bibliography: bibliography.bib
csl: cpt-pharmacometrics-and-systems-pharmacology.csl
---

<div custom-style="AuthorUpdate">
Peter Bloomingdale^1^, Antari Khot^2^
</div>

<br>

1. Boehringer Ingelheim, Pharmacometrics, Boston, MA, USA
2. Takeda, Quantitative Clinical Pharmacology, Boston, MA, USA

<br>

<div custom-style="CorrAuthor">
  Corresponding Author:

  Peter Bloomingdale

  Email

  12345 Street, Boston, MA, 02115

  123-456-7890
</div>


Keywords: Pharmacokinetics, Pharmacodynamics

CONFLICT OF INTEREST

*Insert conflict of interest statement*

FUNDING

*Insert funding information*

{{< pagebreak >}}

## ABSTRACT


## INTRODUCTION

## METHODS


## RESULTS


## DISCUSSION


## STUDY HIGHLIGHTS

*Articles should include a Study Highlights section after the Discussion in the manuscript text. The highlights section should include and answer each of the questions below. The entire section, not including the questions, should be under 150 words.*

* What is the current knowledge on the topic?

*Answer*

* What question did this study address?

*Answer*

* What does this study add to our knowledge?

*Answer*

* How might this change drug discovery, development, and/or therapeutics?

*Answer*


## ACKNOWLEDGEMENTS


## AUTHOR CONTRIBUTIONS

Please use the following template for author contributions. Contributions that do not fall into these categories may be included in the Acknowledgements section. 
X.X., X.Y., and X.Z. wrote the manuscript; X.X. designed the research; X.X. and X.Y. performed the research; X.Z. analyzed the data; X.X., X.Y., and X.Z. contributed new reagents/analytical tools.


## REFERENCES

::: {#refs}

:::


## FIGURE LEGENDS


## SUPPLEMENTARY MATERIALS

Insert titles and legends of all supplementary materials. Please do not label your supplementary materials as appendices and label your supplementary materials according to the naming structure shown below

*Figure S1*

*Table S1*

*Model Code*

*Supplementary Materials*

## Additional Notes:

### Equations
$$
E = mc^{2}
$$ {#eq-eqn1}

### How to add references

This paper is really cool, but you will probably fall asleep reading it [@bloomingdale2018boolean]!

The easiest way to add references is to go to [Google Scholar](https://scholar.google.com/). Click the "Cite" icon under the paper of interest. Copy the **BibTex** text and paste it into the bibliography.bib file.
